# Generated by Django 3.0.8 on 2020-08-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_team', models.CharField(max_length=40)),
                ('key_player', models.CharField(max_length=40)),
            ],
        ),
    ]
